//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingWing.PgSql.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SingWing.PgSql.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 An abnormal heartbeat to {0} was detected. 的本地化字符串。
        /// </summary>
        internal static string AbnormalHeartbeatDetected {
            get {
                return ResourceManager.GetString("AbnormalHeartbeatDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Another transaction is running on the connection. 的本地化字符串。
        /// </summary>
        internal static string AnotherTransactionIsRunning {
            get {
                return ResourceManager.GetString("AnotherTransactionIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authentication to database &quot;{0}@{1}:{2}/{3}&quot; failed. 的本地化字符串。
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command text is empty. 的本地化字符串。
        /// </summary>
        internal static string CommandTextIsEmpty {
            get {
                return ResourceManager.GetString("CommandTextIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection has been disconnected. 的本地化字符串。
        /// </summary>
        internal static string ConnectionDisconnected {
            get {
                return ResourceManager.GetString("ConnectionDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to connect to &quot;{0}:{1}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection is not ready to execute commands. 的本地化字符串。
        /// </summary>
        internal static string ConnectionNotReady {
            get {
                return ResourceManager.GetString("ConnectionNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection string is empty. 的本地化字符串。
        /// </summary>
        internal static string ConnectionStringIsEmpty {
            get {
                return ResourceManager.GetString("ConnectionStringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The database name exceeds {0} characters. 的本地化字符串。
        /// </summary>
        internal static string DatabaseNameExceedsLimit {
            get {
                return ResourceManager.GetString("DatabaseNameExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The database name is empty. 的本地化字符串。
        /// </summary>
        internal static string DatabaseNameIsEmpty {
            get {
                return ResourceManager.GetString("DatabaseNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The database {0} is too busy. 的本地化字符串。
        /// </summary>
        internal static string DatabaseTooBusy {
            get {
                return ResourceManager.GetString("DatabaseTooBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data type code {0} is not supported. 的本地化字符串。
        /// </summary>
        internal static string DataTypeNotSupported {
            get {
                return ResourceManager.GetString("DataTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get IP addresses of {0}. 的本地化字符串。
        /// </summary>
        internal static string FailedToGetIPAddresses {
            get {
                return ResourceManager.GetString("FailedToGetIPAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The hosts contains invalid host information. 的本地化字符串。
        /// </summary>
        internal static string InvalidHosts {
            get {
                return ResourceManager.GetString("InvalidHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Needs to call MoveNextAsync first. 的本地化字符串。
        /// </summary>
        internal static string NeedsToCallMoveNext {
            get {
                return ResourceManager.GetString("NeedsToCallMoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is not enough buffer space. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughBufferSpace {
            get {
                return ResourceManager.GetString("NotEnoughBufferSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation has timed out. 的本地化字符串。
        /// </summary>
        internal static string OperationTimeout {
            get {
                return ResourceManager.GetString("OperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user password exceeds {0} characters. 的本地化字符串。
        /// </summary>
        internal static string PasswordExceedsLimit {
            get {
                return ResourceManager.GetString("PasswordExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roll back transaction failed. 的本地化字符串。
        /// </summary>
        internal static string RollbackTransactionFailed {
            get {
                return ResourceManager.GetString("RollbackTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The save point name is empty. 的本地化字符串。
        /// </summary>
        internal static string SavepointNameIsEmpty {
            get {
                return ResourceManager.GetString("SavepointNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of stream exceeds {0} GiB. 的本地化字符串。
        /// </summary>
        internal static string StreamLengthExceedsLimit {
            get {
                return ResourceManager.GetString("StreamLengthExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The terminator(&apos;\0&apos;) of the string was not found. 的本地化字符串。
        /// </summary>
        internal static string StringTerminatorNotFound {
            get {
                return ResourceManager.GetString("StringTerminatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The server {0} reported an too_many_connections ({1}/{2}) error. 的本地化字符串。
        /// </summary>
        internal static string TooManyConnectionsWarning {
            get {
                return ResourceManager.GetString("TooManyConnectionsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of parameters exceeds {0}. 的本地化字符串。
        /// </summary>
        internal static string TooManyParameters {
            get {
                return ResourceManager.GetString("TooManyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The transaction has ended or has not been started. 的本地化字符串。
        /// </summary>
        internal static string TransactionNotRunning {
            get {
                return ResourceManager.GetString("TransactionNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown backend message type &apos;{0}&apos;(length: {1}). 的本地化字符串。
        /// </summary>
        internal static string UnknownBackendMessage {
            get {
                return ResourceManager.GetString("UnknownBackendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The database user name exceeds {0} characters. 的本地化字符串。
        /// </summary>
        internal static string UserNameExceedsLimit {
            get {
                return ResourceManager.GetString("UserNameExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user name is empty. 的本地化字符串。
        /// </summary>
        internal static string UserNameIsEmpty {
            get {
                return ResourceManager.GetString("UserNameIsEmpty", resourceCulture);
            }
        }
    }
}
